#!/usr/bin/env bash
#. $(dirname $0)/init_create_crmsh.ini
BASENAME="$(basename $0)"
SHELL_PWD_PATH="$(cd $(dirname $0);pwd -P)"
SHELL_LIKE="$(ls -l ${SHELL_PWD_PATH}/${BASENAME}|awk -F'>' '{print $2}')"
[ -z ${SHELL_LIKE} ] || SHELL_PWD_PATH=$(dirname ${SHELL_LIKE})
HA_DIR="${SHELL_PWD_PATH%/*}"
HA_RUN="$HA_DIR/run"
HA_CONF="$HA_DIR/etc"
HA_SBIN="$HA_DIR/sbin"
HA_PLUGIN="$HA_DIR/plugin"
HA_MESSAGE="$HA_SBIN/message_agent"
HA_LOG="$HA_DIR/log"
HA_TEMP="$HA_DIR/template"
HA_TMP="$HA_DIR/tmp"

#[ -f $HA_CONF/init_create_crmsh.ini ] && . $HA_CONF/init_create_crmsh.ini || {
[ -f $HA_CONF/ha_conf.ini ] && . $HA_CONF/ha_conf.ini || {
	echo "$(date +'%F %H:%M:%S') $(hostname) 初始化参数 $HA_CONF/ha_conf.ini 未找到。" | $HA_MESSAGE ERR INIT
	exit 1
	}
DISK_SCAN_CHECK

for i in EMAIL_SJ EMAIL_VIP EMAIL_VIP_DEV EMAIL_VIP_NET EMAIL_SER_N HA_PING_GW SSH_PORT CHECK_SEND_MESSAGE EMAIL_SERVER FROM FROM_PASS TO EYOU_NETWORK_CHECK EYOU_DISK_XT_STATUS EYOU_DISK_NFS_XT DISK_NUM DISK_MOUNT_1 HA_SERVER
do
test_i="$(eval echo \$${i})"
[ -z "${test_i}" ] && {
        echo "$(date +'%F %H:%M:%S') $(hostname) 初始化参数 $i 参数为空" | $HA_MESSAGE ERR INIT
        exit 1
        }
echo $test_i
done
unset i
unset test_i


CONFIG_FILE="/usr/local/eyou/mail/etc/em_init_config"
if [ ${HA_SERVER} != "gateway" ] && [ -f $CONFIG_FILE ];then
 . $CONFIG_FILE 
elif [ ${HA_SERVER} == "gateway" ];then
	:
else
 exit 123
fi

[ -f $HA_TEMP/crmsh ] && mv $HA_TEMP/crmsh $HA_TEMP/crmsh.$(date +%F).$(date +%s).old

sysconfig_crm () {
echo '
crm configure rsc_defaults resource-stickiness=100 failure-timeout=14400s target-role=Stopped
wait;
crm configure op_defaults timeout=300s
wait;
crm configure property stonith-enabled=false no-quorum-policy=ignore
wait;
'
#for i in `seq $DISK_NUM`
#do
#if [ "$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f1|grep ':'|wc -l)" == "0" ];then
#crm configure primitive eyou_mount_disk_${i} ocf:heartbeat:Filesystem params device=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f1) directory=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f2) fstype=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f3) op start interval=0 timeout=60 op stop interval=0 timeout=60 meta migration-threshold=5 resource-stickiness=10 failure-timeout=300s

echo "
crm configure primitive eyou_mount_disk lsb:eyou_mount \
	op monitor interval=5s timeout=15s \
	meta migration-threshold=2 resource-stickiness=10
"
echo "wait;"
#else
#echo "
#crm configure primitive eyou_mount_disk_${i} ocf:heartbeat:Filesystem params device=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f1) directory=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f2) fstype=$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f3) options=nolock,tcp op start interval=0 timeout=60 op stop interval=0 timeout=60 meta migration-threshold=5 resource-stickiness=10 failure-timeout=300s
#crm configure clone eyou_mount_clone_${i} eyou_mount_disk_${i} meta globally-unique=false
#"
#fi
#done
echo "
crm configure primitive eyou_mail_vip ocf:heartbeat:IPaddr2 params ip=$EMAIL_VIP nic=$EMAIL_VIP_DEV cidr_netmask=$EMAIL_VIP_NET op monitor interval=30s
wait;
crm configure primitive pingd ocf:pacemaker:ping params host_list=$HA_PING_GW multiplier=100 name=pingd op monitor interval=15s timeout=60s
wait;
"
#echo '
#crm configure primitive eyou_check_disk_port lsb:eyou_check_disk_port \
#        op monitor interval=5s timeout=15s \
#        meta migration-threshold=2 resource-stickiness=10
#'
#echo '
#crm configure primitive eyou_check_disk lsb:eyou_check_disk \
#        op monitor interval=5s timeout=15s \
#        meta migration-threshold=1 resource-stickiness=10 failure-timeout=300s
#'
echo '
crm configure primitive eyou_check_network lsb:eyou_check_network \
        op monitor interval=5s timeout=15s
wait;
crm configure clone eyou_check_clone eyou_check_network \
        meta globally-unique="false"
wait;
'
echo '
crm configure clone pingdclone pingd \
        meta globally-unique="false"
wait;
crm configure location eyou_check_network_l eyou_check_clone \
        rule -inf: not_defined pingd or pingd lte 0
wait;
crm configure location eyou_ping_l eyou_mail_vip \
        rule -inf: not_defined pingd or pingd lte 0
wait;
'
<<lgp_disable
if [ "$DISK_NUM" == "1" ] && [ "$DISK_TYPE" == "ext" ];then
echo "#ext =1"
#	echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_mount_disk_${DISK_NUM} eyou_check_disk"
#	echo "crm configure order eyou_mount_after inf: eyou_check_disk eyou_mount_disk_${DISK_NUM} eyou_mail_vip"
	echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_mount_disk"
	echo "crm configure order eyou_mount_after inf: eyou_mount_disk eyou_mail_vip"
elif [ "$DISK_NUM" == "1" ] && [ "$DISK_TYPE" == "nfsext" ];then
echo "#nfsext =1"
	echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_mount_disk_${DISK_NUM} eyou_check_disk"
	echo "crm configure order eyou_mount_after inf: eyou_check_disk eyou_mount_disk_${DISK_NUM} eyou_mail_vip"
elif [ "$DISK_NUM" -gt "1" ] && [ "$DISK_TYPE" == "ext" ];then
	echo "#ext gt 1"
		EYOU_MOUNT_DISK=$(for i in `seq $DISK_NUM`;do echo eyou_mount_disk_${i}; done)
		echo "crm configure colocation eyou_disk_colo inf: "${EYOU_MOUNT_DISK}
		echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_mount_disk_${DISK_NUM} eyou_check_disk"
		for i in `seq $DISK_NUM`
		do
		echo "crm configure order eyou_mount_after_${i} inf: eyou_check_disk eyou_mount_disk_${i} eyou_mail_vip"
		done
	elif [ "$DISK_NUM" -gt "1" ] && [ "$DISK_TYPE" == "nfsext" ];then
	echo "#nfsext  gt 1"
		EYOU_MOUNT_DISK=$(for i in `seq $DISK_NUM`;do echo eyou_mount_disk_${i}; done)
		echo "crm configure colocation eyou_disk_colo inf: "${EYOU_MOUNT_DISK}
		echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_mount_disk_${DISK_NUM} eyou_check_disk"
		for i in `seq $DISK_NUM`
		do
		echo "crm configure order eyou_mount_after_${i} inf: eyou_check_disk eyou_mount_disk_${i} eyou_mail_vip"
		done
	elif [ "$DISK_NUM" == "1" ] && [ "$DISK_TYPE" == "nfs" ];then
	echo "#nfs =1"
#		echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_mount_clone_${DISK_NUM} eyou_check_disk"
		echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_check_disk"
		echo "crm configure order eyou_mount_after inf: eyou_mount_clone_${DISK_NUM}  eyou_check_disk eyou_mail_vip"
	elif [ "$DISK_NUM" -gt "1" ] && [ "$DISK_TYPE" == "nfs" ];then
	echo "#nfs gt 1"
		EYOU_MOUNT_DISK=$(for i in `seq $DISK_NUM`;do echo eyou_mount_disk_${i}; done)
#		echo "crm configure colocation eyou_disk_colo inf: "${EYOU_MOUNT_DISK}
#		echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_mount_clone_${DISK_NUM} eyou_check_disk"
		echo "crm configure colocation eyou_mount_colo inf: eyou_mail_vip eyou_check_disk"
		for i in `seq $DISK_NUM`
		do
		echo "crm configure order eyou_mount_after_${i} inf: eyou_mount_clone_${i} eyou_check_disk eyou_mail_vip"
		done
	else
		:

	fi
lgp_disable
echo 'crm configure colocation eyou_disk_colo inf: eyou_mount_disk eyou_mail_vip'
echo "wait;"
echo 'crm configure order eyou_disk_after inf: eyou_mount_disk eyou_mail_vip'
echo "wait;"

}

eyou_crm () {
for i in ${ARRAY_START[@]}
do
	[[ "$i" =~ "cron_etc" ]] && {
	echo "crm configure primitive eyou_$i lsb:eyou_mail_$i op monitor interval=1m timeout=60s"
	echo "wait;"
	} || {
	echo "crm configure primitive eyou_$i lsb:eyou_mail_$i op monitor interval=1m timeout=60s meta migration-threshold=5 resource-stickiness=10"
	echo "wait;"
	}
done

echo '
crm configure primitive send_email lsb:eyou_check_sendemail \
        op monitor interval="30s" timeout="60s"
'
echo "wait;"
}

eyou_clo_lo () {
if [[ "${ARRAY_START[@]} " =~ "filedrepd " ]];then
echo '
crm configure clone eyou_filedrepd_clone eyou_filedrepd \
        meta globally-unique="false"
'
echo "wait;"
fi

	echo '
#crm configure order ms_mount_nfs_after inf: eyou_mount_nfs eyou_check_disk eyou_mail_vip

crm configure order eyou_vip_check_after inf: eyou_mail_vip eyou_check_clone
wait;
'
if [[ "${ARRAY_START[@]} " =~ "mysql " ]];then
echo '
crm configure colocation eyou_mysql_colo inf: eyou_mail_vip eyou_mysql send_email
wait;
crm configure order eyou_mysql_after inf: eyou_mail_vip eyou_mysql eyou_mproxy
wait;
crm configure order eyou_mysql_sendemail inf: eyou_mysql send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "mysql_index " ]];then
echo '
crm configure colocation eyou_mysql_index_colo inf: eyou_mail_vip eyou_mysql_index send_email
wait;
crm configure order eyou_mysql_index_after inf: eyou_mail_vip eyou_mysql_index eyou_mproxy_index
wait;
crm configure order eyou_mysql_index_sendemail inf: eyou_mysql_index send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "mysql_log " ]];then
echo '
crm configure colocation eyou_mysql_log_colo inf: eyou_mail_vip eyou_mysql_log send_email
wait;
crm configure order eyou_mysql_log_after inf: eyou_mail_vip eyou_mysql_log
wait;
crm configure order eyou_mysql_log_sendemail inf: eyou_mysql_log send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "mproxy " ]];then
echo '
crm configure colocation eyou_mproxy_colo inf: eyou_mail_vip eyou_mproxy send_email
wait;
crm configure order eyou_mproxy_sendemail inf: eyou_mproxy send_email
wait;
'
fi

if [[ "${ARRAY_START[@]} " =~ "mproxy_index " ]];then
echo '
crm configure colocation eyou_mproxy_index_colo inf: eyou_mail_vip eyou_mproxy_index send_email
wait;
crm configure order eyou_mproxy_index_sendemail inf: eyou_mproxy_index send_email
wait;
'
fi

if [[ "${ARRAY_START[@]} " =~ "memcache_fix " ]];then
echo '
crm configure colocation eyou_memcache_fix_colo inf: eyou_mail_vip eyou_memcache_fix send_email
wait;
crm configure order eyou_memcache_fix_after inf: eyou_mysql eyou_memcache_fix
wait;
crm configure order eyou_memcache_fix_sendemail inf: eyou_memcache_fix send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "memcache_hot " ]];then
echo '
crm configure colocation eyou_memcache_hot_colo inf: eyou_mail_vip eyou_memcache_hot send_email
wait;
crm configure order eyou_memcache_hot_after inf: eyou_mysql eyou_memcache_hot
wait;
crm configure order eyou_memcache_hot_sendemail inf: eyou_memcache_hot send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "memcache_session " ]];then
echo '
crm configure colocation eyou_memcache_session_colo inf: eyou_mail_vip eyou_memcache_session send_email
wait;
crm configure order eyou_memcache_session_after inf: eyou_mysql eyou_memcache_session
wait;
crm configure order eyou_memcache_session_sendemail inf: eyou_memcache_session send_email
wait;
'
fi

if [[ "${ARRAY_START[@]} " =~ "gearman " ]];then
echo '
crm configure colocation eyou_gearman_colo inf: eyou_mail_vip eyou_gearman send_email
wait;
crm configure order eyou_gearman_after inf: eyou_mysql eyou_gearman
wait;
crm configure order eyou_gearman_sendemail inf: eyou_gearman send_email
wait;
'
fi

if [[ "${ARRAY_START[@]} " =~ "bounce " ]];then
echo '
crm configure colocation eyou_bounce_colo inf: eyou_mail_vip eyou_bounce send_email
wait;
crm configure order eyou_bounce_after1 inf: eyou_mproxy eyou_bounce
wait;
crm configure order eyou_bounce_after2 inf: eyou_memcache_fix eyou_bounce
wait;
crm configure order eyou_bounce_after3 inf: eyou_memcache_session eyou_bounce
wait;
crm configure order eyou_bounce_after4 inf: eyou_memcache_hot eyou_bounce
wait;
crm configure order eyou_bounce_sendemail inf: eyou_bounce send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "cron_etc " ]];then
echo '
crm configure colocation eyou_cron_etc_colo inf: eyou_mail_vip eyou_cron_etc send_email
wait;
crm configure order eyou_cron_etc_after inf: eyou_mail_vip eyou_cron_etc
wait;
crm configure order eyou_cron_etc_sendemail inf: eyou_cron_etc send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "cleanup " ]];then
echo '
crm configure colocation eyou_cleanup_colo inf: eyou_mail_vip eyou_cleanup send_email
wait;
crm configure order eyou_cleanup_after inf: eyou_mail_vip eyou_cleanup
wait;
crm configure order eyou_cleanup_sendemail inf: eyou_cleanup send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "crtmpd " ]];then
echo '
crm configure colocation eyou_crtmpd_colo inf: eyou_mail_vip eyou_crtmpd send_email
wait;
crm configure order eyou_crtmpd_after inf: eyou_mail_vip eyou_crtmpd
wait;
crm configure order eyou_crtmpd_sendemail inf: eyou_crtmpd send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "filedagent " ]];then
echo '
crm configure colocation eyou_filedagent_colo inf: eyou_mail_vip eyou_filedagent send_email
wait;
crm configure order eyou_filedagent_after inf: eyou_mail_vip eyou_filedagent
wait;
crm configure order eyou_filedagent_sendemail inf: eyou_filedagent send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "filed " ]];then
echo '
crm configure colocation eyou_filed_colo inf: eyou_mail_vip eyou_filed send_email
wait;
crm configure order eyou_filed_after inf: eyou_mail_vip eyou_filed
wait;
crm configure order eyou_filed_sendemail inf: eyou_filed send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "filedrepd " ]];then
echo '
crm configure order eyou_filedrepd_sendemail inf: eyou_filedrepd_clone send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "httpd " ]];then
echo '
crm configure colocation eyou_httpd_colo inf: eyou_mail_vip eyou_httpd send_email
wait;
crm configure order eyou_httpd_after inf: eyou_mail_vip eyou_httpd
wait;
crm configure order eyou_httpd_sendemail inf: eyou_httpd send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "imap " ]];then
echo '
crm configure colocation eyou_imap_colo inf: eyou_mail_vip eyou_imap send_email
wait;
crm configure order eyou_imap_after inf: eyou_mproxy eyou_imap
wait;
crm configure order eyou_imap_sendemail inf: eyou_imap send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "local " ]];then
echo '
crm configure colocation eyou_local_colo inf: eyou_mail_vip eyou_local send_email
wait;
crm configure order eyou_local_after1 inf: eyou_mproxy eyou_local
wait;
crm configure order eyou_local_after2 inf: eyou_memcache_fix eyou_local
wait;
crm configure order eyou_local_after3 inf: eyou_memcache_session eyou_local
wait;
crm configure order eyou_local_after4 inf: eyou_memcache_hot eyou_local
wait;
crm configure order eyou_local_sendemail inf: eyou_local send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "mlist " ]];then
echo '
crm configure colocation eyou_mlist_colo inf: eyou_mail_vip eyou_mlist send_email
wait;
crm configure order eyou_mlist_after1 inf: eyou_mproxy eyou_mlist
wait;
crm configure order eyou_mlist_after2 inf: eyou_memcache_fix eyou_mlist
wait;
crm configure order eyou_mlist_after3 inf: eyou_memcache_session eyou_mlist
wait;
crm configure order eyou_mlist_after4 inf: eyou_memcache_hot eyou_mlist
wait;
crm configure order eyou_mlist_sendemail inf: eyou_mlist send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "nginx " ]];then
echo '
crm configure colocation eyou_nginx_colo inf: eyou_mail_vip eyou_nginx send_email
wait;
crm configure order eyou_nginx_after inf: eyou_mail_vip eyou_nginx
wait;
crm configure order eyou_nginx_sendemail inf: eyou_nginx send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "phpd " ]];then
echo '
crm configure colocation eyou_phpd_colo inf: eyou_mail_vip eyou_phpd send_email
wait;
crm configure order eyou_phpd_after1 inf: eyou_mysql_log eyou_phpd
wait;
crm configure order eyou_phpd_after2 inf: eyou_gearman eyou_phpd
wait;
crm configure order eyou_phpd_sendemail inf: eyou_phpd send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "pop " ]];then
echo '
crm configure colocation eyou_pop_colo inf: eyou_mail_vip eyou_pop send_email
wait;
crm configure order eyou_pop_after inf: eyou_mproxy eyou_pop
wait;
crm configure order eyou_pop_sendemail inf: eyou_pop send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "remote " ]];then
echo '
crm configure colocation eyou_remote_colo inf: eyou_mail_vip eyou_remote send_email
wait;
crm configure order eyou_remote_after1 inf: eyou_mproxy eyou_remote
wait;
crm configure order eyou_remote_after2 inf: eyou_memcache_fix eyou_remote
wait;
crm configure order eyou_remote_after3 inf: eyou_memcache_session eyou_remote
wait;
crm configure order eyou_remote_after4 inf: eyou_memcache_hot eyou_remote
wait;
crm configure order eyou_remote_sendemail inf: eyou_remote send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "smtp " ]];then
echo '
crm configure colocation eyou_smtp_colo inf: eyou_mail_vip eyou_smtp send_email
wait;
crm configure order eyou_smtp_after inf: eyou_mproxy eyou_smtp
wait;
crm configure order eyou_smtp_sendemail inf: eyou_smtp send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "syslog " ]];then
echo '
crm configure colocation eyou_syslog_colo inf: eyou_mail_vip eyou_syslog send_email
wait;
crm configure order eyou_syslog_after inf: eyou_mail_vip eyou_syslog
wait;
crm configure order eyou_syslog_sendemail inf: eyou_syslog send_email
wait;
'
fi
if [[ "${ARRAY_START[@]} " =~ "rsyslogd " ]];then
echo '
crm configure colocation eyou_rsyslogd_colo inf: eyou_mail_vip eyou_rsyslogd send_email
wait;
crm configure order eyou_rsyslogd_after inf: eyou_mail_vip eyou_rsyslogd
wait;
crm configure order eyou_rsyslogd_sendemail inf: eyou_rsyslogd send_email
wait;
'
fi

}

gateway_crm () {
echo '
crm configure primitive eyou_gateway lsb:eyou_gateway op monitor interval=1m timeout=300s
wait;
crm configure colocation eyou_gateway_colo inf: eyou_mail_vip eyou_gateway
wait;
crm configure order eyou_gateway_after inf: eyou_mail_vip eyou_gateway
wait;
'
}


sysconfig_crm >>$HA_TEMP/crmsh
[ "$HA_SERVER" == "mail" ] && {
	eyou_crm >>$HA_TEMP/crmsh
	eyou_clo_lo >>$HA_TEMP/crmsh
	}
[ "$HA_SERVER" == "gateway" ] && {
	gateway_crm >>$HA_TEMP/crmsh
	}
[ "$HA_SERVER" == "2in1" ] && {
	eyou_crm >>$HA_TEMP/crmsh
	eyou_clo_lo >>$HA_TEMP/crmsh
	gateway_crm >>$HA_TEMP/crmsh
	}


exit 0
