#!/usr/bin/env bash
#by liguopeng email:liguopeng@eyou.net
#by zh_CN.UTF8
BASENAME="$(basename $0)"
SHELL_PWD_PATH="$(cd $(dirname $0);pwd -P)"
SHELL_LIKE="$(ls -l ${SHELL_PWD_PATH}/${BASENAME}|awk -F'>' '{print $2}')"
[ -z ${SHELL_LIKE} ] || SHELL_PWD_PATH=$(dirname ${SHELL_LIKE})
HA_DIR="${SHELL_PWD_PATH%/*}"
HA_RUN="$HA_DIR/run"
HA_CONF="$HA_DIR/etc"
HA_SBIN="$HA_DIR/sbin"
HA_PLUGIN="$HA_DIR/plugin"
HA_MESSAGE="$HA_SBIN/message_agent"
HA_LOG="$HA_DIR/log"
HA_TEMP="$HA_DIR/template"
HA_TMP="$HA_DIR/tmp"
pid_name="$(basename $0).pid"

[ -f $HA_SBIN/check_master_slave ] && . $HA_SBIN/check_master_slave || {
                echo "$DATE_MESS $(hostname) $EYOU_SYS_NAME 检测 $HA_SBIN/check_master_slave 不存在。"|$HA_MESSAGE ERR EYOU_MAIL $EYOU_SER_FILE_CONF
                exit 121
        }

if [ $(echo $EYOU_DISK_XT|grep '^-U '|wc -l) == "1" ];then
        EYOU_DISK_TEST=$(echo $EYOU_DISK_XT|awk '{print $2}')
        EYOU_DISK_XT="/dev/disk/by-uuid/$(ls -l /dev/disk/by-uuid |grep $EYOU_DISK_TEST|awk -F '->' '{print $2}'|sed 's/ //g')"
fi

#获取当前时间戳,并且制定check格式
CHECK_TIME () {
echo "1 $(date +%s)"
}

#启动时候检查动作
start_check () {

[ -f ${EYOU_CHECK_DISK_XT} ] && rm -rf ${EYOU_CHECK_DISK_XT}
[ $(echo -e "${EYOU_DISK_XT}"|grep \/|wc -l) -eq 0 ] && exit 119
fdisk -l ${EYOU_DISK_XT} >/dev/null  2>&1 || exit 133
DISK_TEST_SIZ=$(fdisk -l ${EYOU_DISK_XT} |grep "${EYOU_DISK_XT}"|awk '{print $5}')
if [ -z ${DISK_TEST_SIZ} ];then echo "$(date +%'F %H:%M:%S') $(hostname) $EYOU_DISK_XT 心跳磁盘未找到。"|$HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF; exit 123;fi
if [ "${DISK_TEST_SIZ}" -gt "1569792000" ];then echo "$(date +%'F %H:%M:%S') $(hostname) $EYOU_DISK_XT 磁盘大小大于1500M...."|$HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF; exit 123;fi
#lgp_add skip=b
#dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 >/dev/null 2>&1;
#until [ -f ${EYOU_CHECK_DISK_XT} ];do dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 >/dev/null 2>&1;done
dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 skip=b >/dev/null 2>&1;
until [ -f ${EYOU_CHECK_DISK_XT} ];do dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 skip=b >/dev/null 2>&1;done

CHECK_FILE=${EYOU_CHECK_DISK_XT}
check_time_disk_1=$(crm configure show xml |grep eyou_mount_disk|grep monitor|awk -F'=' '{print $3}'|cut -d \" -f2|grep -io "[0-9]\{1,3\}"|head -1)
check_time_disk=$(echo "${check_time_disk_1}"-5|bc)

#lgp_add seek=b
#	if [ "$(head -1 $CHECK_FILE|awk '{print $1}')" != "1" ];then CHECK_TIME > $EYOU_CHECK_DISK_XT 2>/dev/null;dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} bs=1K count=1024 >/dev/null 2>&1;echo "$(date +%'F %H:%M:%S') $(hostname) ${EYOU_DISK_XT} 内容非标准 跳过检查 ，将执行mount动作"|$HA_MESSAGE OK DISK $CHECK_DISK_SCAN_CONF; exit_val=0; else exit_val=1;fi
	if [ "$(head -1 $CHECK_FILE|awk '{print $1}')" != "1" ];then CHECK_TIME > $EYOU_CHECK_DISK_XT 2>/dev/null;dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} bs=1K count=1024 seek=b >/dev/null 2>&1;echo "$(date +%'F %H:%M:%S') $(hostname) ${EYOU_DISK_XT} 内容非标准 跳过检查 ，将执行mount动作"|$HA_MESSAGE OK DISK $CHECK_DISK_SCAN_CONF; exit_val=0; else exit_val=1;fi
	if [ $exit_val == "1" ];then

		#lgp_add skip=b
		#dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 >/dev/null 2>&1
		#until [ -f ${EYOU_CHECK_DISK_XT} ];do dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 >/dev/null 2>&1;done
		dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 skip=b >/dev/null 2>&1
		until [ -f ${EYOU_CHECK_DISK_XT} ];do dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 skip=b >/dev/null 2>&1;done

		cat_disk_1=$(head -1 $CHECK_FILE)
		sleep $check_time_disk ;wait

		#lgp_add skip=b
		#dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 >/dev/null 2>&1
		#until [ -f ${EYOU_CHECK_DISK_XT} ];do dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 >/dev/null 2>&1;done
		dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 skip=b >/dev/null 2>&1
		until [ -f ${EYOU_CHECK_DISK_XT} ];do dd if=${EYOU_DISK_XT} of=${EYOU_CHECK_DISK_XT} bs=1K count=1024 skip=b >/dev/null 2>&1;done
		cat_disk_2=$(head -1 $CHECK_FILE)
		if [ "$cat_disk_1" == "$cat_disk_2" ];then
			echo "$(date +%'F %H:%M:%S') $(hostname) $EYOU_DISK_XT 磁盘在规定时间内未有改动，将执行mount挂载动作."|$HA_MESSAGE OK DISK $CHECK_DISK_SCAN_CONF
			CHECK_TIME > $EYOU_CHECK_DISK_XT 2>/dev/null

			#lgp_add seek=b
			#dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} bs=1K count=1024 >/dev/null 2>&1
			dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} bs=1K count=1024 seek=b >/dev/null 2>&1
			exit_val=0
		else
			echo "$(date +%'F %H:%M:%S') $(hostname) $EYOU_DISK_XT 磁盘在规定时间内有改动，停止启动,退出."|$HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF
			exit 1;
		fi
	fi
[ $exit_val -eq 0 ] && touch $HA_RUN/$pid_name
}

#主机服务启动之后 检测状态时更新文件
status_check () {
[ $(echo -e "${EYOU_DISK_XT}"|grep \/|wc -l) -eq 0 ] && exit 119
fdisk -l ${EYOU_DISK_XT} >/dev/null  2>&1 || exit 133
DISK_TEST_SIZ=$(fdisk -l ${EYOU_DISK_XT} |grep "${EYOU_DISK_XT}"|awk '{print $5}')
if [ -z ${DISK_TEST_SIZ} ];then echo "$(date +%'F %H:%M:%S') $(hostname) $EYOU_DISK_XT 心跳磁盘未找到。"|$HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF; exit 123;fi
if [ "${DISK_TEST_SIZ}" -gt "1569792000" ];then echo "$(date +%'F %H:%M:%S') $(hostname) $EYOU_DISK_XT 磁盘大小大于1500M...."|$HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF; exit 123;fi
[ -f "$EYOU_CHECK_DISK_XT" ] || exit 113

#lgp_add skip=b
#dd if=${EYOU_DISK_XT} of=/tmp/.test_disk_check bs=1K count=1024 >/dev/null 2>&1
#until [ -f /tmp/.test_disk_check ];do dd if=${EYOU_DISK_XT} of=/tmp/.test_disk_check bs=1K count=1024 >/dev/null 2>&1;done
dd if=${EYOU_DISK_XT} of=/tmp/.test_disk_check bs=1K count=1024 skip=b >/dev/null 2>&1
until [ -f /tmp/.test_disk_check ];do dd if=${EYOU_DISK_XT} of=/tmp/.test_disk_check bs=1K count=1024 skip=b >/dev/null 2>&1;done

if [ "$(head -1 /tmp/.test_disk_check|cut -d ' ' -f2)" == "$(head -1 $EYOU_CHECK_DISK_XT|cut -d ' ' -f2)" ];then
	rm -rf /tmp/.test_disk_check
else
	echo "$(date +%'F %H:%M:%S') $(hostname) ${EYOU_DISK_XT} 上一次的磁盘数据非本机修改，退出。"|$HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF
	exit 110
fi
CHECK_FILE=${EYOU_CHECK_DISK_XT}
check_time_disk_1=$(crm configure show xml |grep eyou_mount_disk|grep monitor|awk -F'=' '{print $3}'|cut -d \" -f2|grep -io "[0-9]\{1,3\}"|head -1)
check_time_disk=$(echo "${check_time_disk_1}"+2|bc)
	CHECK_TIME>$CHECK_FILE 2>/dev/null

	#lgp_add seek=b
	#dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} bs=1K count=1024 >/dev/null 2>&1 && exit_val=0 || exit_val=1
	dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} bs=1K count=1024 seek=b >/dev/null 2>&1 && exit_val=0 || exit_val=1

#	exit_val=$?
if [ $exit_val -eq 0 ];then
	:
else
	echo "$(date +%'F %H:%M:%S') $(hostname) $EYOU_DISK_XT 磁盘数据 写入失败. 等待再次执行结果. 第一次." | $HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF
	#lgp_add seek=b
	#if dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} bs=1K count=1024 >/dev/null 2>&1;then exit_val=$? ;else echo "$(date +%'F %H:%M:%S') $(hostname) $EYOU_DISK_XT 磁盘数据写入失败.停止所有服务. 第二次."|$HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF;exit 1;fi
	if dd if=${EYOU_CHECK_DISK_XT} of=${EYOU_DISK_XT} bs=1K count=1024 seek=b >/dev/null 2>&1;then exit_val=$? ;else echo "$(date +%'F %H:%M:%S') $(hostname) $EYOU_DISK_XT 磁盘数据写入失败.停止所有服务. 第二次."|$HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF;exit 1;fi
fi
}

stop_check () {
if [ -f $HA_RUN/$pid_name ];then
DISK_PATH=$(fdisk -l ${EYOU_DISK_XT}|grep -o ${EYOU_DISK_XT})

#lgp_add modify seek=b touch
#[ -z "$DISK_PATH" ] || dd if=/dev/zero of=${EYOU_DISK_XT} bs=1K count=1024 >/dev/null 2>&1
echo > /tmp/.test_disk_check_stop
echo >> /tmp/.test_disk_check_stop
[ -z "$DISK_PATH" ] || dd if=/tmp/.test_disk_check_stop of=${EYOU_DISK_XT} bs=1K count=1024 seek=b >/dev/null 2>&1
rm -rf /tmp/.test_disk_check_stop

else
	:
fi
rm -rf ${EYOU_CHECK_DISK_XT}
exit_val=0

rm -rf $HA_RUN/$pid_name
}
check_disk_status () {
if [ ${EYOU_DISK_XT_STATUS} -eq "0" ];then
	[ "$1" == "status" ] || echo "$(date +%'F %H:%M:%S') $(hostname) 跳过磁盘心跳的检测。"| $HA_MESSAGE OK DISK $CHECK_DISK_SCAN_CONF
	[ "$1" == "start" ] && touch $HA_RUN/$pid_name
	[ "$1" == "stop" ] && rm -rf $HA_RUN/$pid_name
	exit_val=0
elif [ ${EYOU_DISK_XT_STATUS} -eq "1" ];then
	wait
fi
}
	case $1 in
		start)
			check_disk_status start
			#check_crm
			[ $EYOU_DISK_XT_STATUS -eq 1 ] && {
			start_check
			}
		;;
		status)
			[ -f $HA_RUN/$pid_name ] || {
				echo "$(date +%'F %H:%M:%S') $(hostname) 心跳盘状态检测。 $HA_RUN/$pid_name 文件不存在 " | $HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF
				exit 1
			}
			check_disk_status status
			#check_crm
			[ $EYOU_DISK_XT_STATUS -eq 1 ] && {
			status_check
			}
		;;
		stop)
			[ -f $HA_RUN/$pid_name ] || exit 0
			check_disk_status stop
			#check_crm stop
			[ $EYOU_DISK_XT_STATUS -eq 1 ] && {
			stop_check
			}
		;;
		*)
		echo $"Usage: $0 {start|stop|status}";exit 1
		;;
	esac
exit $exit_val
