#!/usr/bin/env bash
#by liguopeng email:liguopeng@eyou.net
#by zh_CN.UTF8
BASENAME="$(basename $0)"
SHELL_PWD_PATH="$(cd $(dirname $0);pwd -P)"
SHELL_LIKE="$(ls -l ${SHELL_PWD_PATH}/${BASENAME}|awk -F'>' '{print $2}')"
[ -z ${SHELL_LIKE} ] || SHELL_PWD_PATH=$(dirname ${SHELL_LIKE})
HA_DIR="${SHELL_PWD_PATH%/*}"
HA_RUN="$HA_DIR/run"
HA_CONF="$HA_DIR/etc"
HA_SBIN="$HA_DIR/sbin"
HA_PLUGIN="$HA_DIR/plugin"
HA_MESSAGE="$HA_SBIN/message_agent"
HA_LOG="$HA_DIR/log"
HA_TEMP="$HA_DIR/template"
HA_TMP="$HA_DIR/tmp"
pid_name="$(basename $0).pid"

#获取当前时间戳,并且制定check格式
CHECK_TIME () {
echo "1 $(date +%s)"
}

[ -f $HA_SBIN/check_master_slave ] && . $HA_SBIN/check_master_slave || {
                echo "$DATE_MESS $(hostname) $EYOU_SYS_NAME 检测 $HA_SBIN/check_master_slave 不存在。"|$HA_MESSAGE ERR EYOU_MAI
L $EYOU_SER_FILE_CONF
                exit 121
        }

#启动时候检查动作
start_check () {
$HA_SBIN/eyou_check_disk_nfs_port status 1
[ $? -eq 0 ] || exit 1

#使用循环检测文件是否存在 存在等待再次检测 如存在 并检查文件变动 退出
for i in $(seq ${DISK_NUM})
	do
	DISK_MOUNT="$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f1)"
	DISK_FILE=$(mount -l |awk '{if($1 == "'${DISK_MOUNT}'") {print $3}}')
	[ -z ${DISK_FILE} ] && exit 1|| CHECK_FILE="$DISK_FILE/$EYOU_DISK_NFS_XT"

	if [ -f $CHECK_FILE ];then
		if [ "$(grep [0-9] $CHECK_FILE|awk '{print $1}')" != "1" ];then CHECK_TIME > $CHECK_FILE 2>/dev/null;echo "$(date +%'F %H:%M:%S') $(hostname) $CHECK_FILE 内容非标准 跳过检查 ，将执行eyou服务启动动作"|$HA_MESSAGE OK DISK $CHECK_DISK_SCAN_CONF; exit_val=0; else exit_val=1;fi
		if [ $exit_val == "1" ];then
			check_time_disk_1=$(crm configure show xml |grep eyou_mount|grep monitor|awk -F'=' '{print $3}'|cut -d \" -f2|grep -io "[0-9]\{1,3\}"|head -1)
			check_time_disk=$(echo "${check_time_disk_1}"+5|bc)
			cat_disk_1=$(cat $CHECK_FILE)
			sleep $check_time_disk;wait
			cat_disk_2=$(cat $CHECK_FILE)
		if [ "$cat_disk_1" == "$cat_disk_2" ];then
			CHECK_TIME > $CHECK_FILE 2>/dev/null
			echo "$(date +%'F %H:%M:%S') $(hostname) $CHECK_FILE 文件在规定时间内未有改动，将执行eyou服务启动动作."|$HA_MESSAGE OK DISK $CHECK_DISK_SCAN_CONF
			exit_val=0
		else
			echo "$(date +%'F %H:%M:%S') $(hostname) $CHECK_FILE 文件在规定时间内有改动，停止启动,退出."|$HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF
			exit_val=1
			exit 1;
		fi
	fi
else
	CHECK_TIME > $CHECK_FILE 2>/dev/null 
	echo "$(date +%'F %H:%M:%S') $(hostname) $CHECK_FILE 文件不存在 跳过检查，将执行eyou服务启动动作." |$HA_MESSAGE OK DISK $CHECK_DISK_SCAN_CONF
		exit_val=0
		
fi
done
[ $exit_val -eq 0 ] && touch $HA_RUN/$pid_name
}

#主机服务启动之后 检测状态时更新文件
status_check () {
$HA_SBIN/eyou_check_disk_nfs_port status 1
[ $? -eq 0 ] || exit 1
for i in $(seq ${DISK_NUM})
        do
        DISK_MOUNT="$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f1)"
	DISK_FILE=$(mount -l |awk '{if($1 == "'${DISK_MOUNT}'") {print $3}}')
	[ -z ${DISK_FILE} ] && exit 1|| CHECK_FILE="$DISK_FILE/$EYOU_DISK_NFS_XT"
	CHECK_TIME>$CHECK_FILE 2>/dev/null && exit_val=0 || exit_val=1
if [ $exit_val -eq 0 ];then
#	exit $exit_val
	:
else
	echo "$(date +%'F %H:%M:%S') $(hostname) $CHECK_FILE 文件 写入失败. 等待再次执行结果. 第一次." |$HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF
	if CHECK_TIME>$CHECK_FILE 2>/dev/null;then exit_val=$? ;else echo "$(date +%'F %H:%M:%S') $(hostname) $CHECK_FILE 文件 写入失败.停止所有服务. 第二次."|$HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF;exit 1;fi
fi
done
}

stop_check () {
if [ -f $HA_RUN/$pid_name ];then
$HA_SBIN/eyou_check_disk_nfs_port status 1
[ $? -eq 0 ] && {
for i in $(seq ${DISK_NUM})
        do
        DISK_MOUNT="$(eval echo \${DISK_MOUNT_${i}}|cut -d ',' -f1)"
	DISK_FILE=$(mount -l |awk '{if($1 == "'${DISK_MOUNT}'") {print $3}}')
	[ -z $DISK_FILE ] && exit 0
	CHECK_FILE="$DISK_FILE/$EYOU_DISK_NFS_XT"
	rm -rf $CHECK_FILE >/dev/null 2>&1
	exit_val=0
done
	}
fi
}

case $1 in
	start)
	start_check
	;;
	status)
	[ -f $HA_RUN/$pid_name ] || {
		echo "$(date +%'F %H:%M:%S') $(hostname) 磁盘心跳检测。$HA_RUN/$pid_name 不存在" | $HA_MESSAGE ERR DISK $CHECK_DISK_SCAN_CONF
		exit_val=1
	}
	[ -z $exit_val ] && status_check
	;;
	stop)
	stop_check
	rm -rf $HA_RUN/$pid_name
	;;
	*)
	echo $"Usage: $0 {start|stop|status}";exit 1
	;;
esac
exit $exit_val
